config/routes.rb
Rails.application.routes.draw do
  get 'feedback/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :feedbacks, only: [:new, :create]
  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true
  validate :validate_answers_count

  belongs_to :test
  has_many :answers

  private

  def validate_answers_count
    errors.add(:answers, 'You must add from 1 to 4 answers') unless (1..4).include?(answers.size)
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[index new create]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def index; end

  def new
    @question = @test.questions.build
  end

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to @question.test
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    redirect_to [:admin, @question.test], notice: 'Question removed successfully'
  end

  def update
    if @question.update(question_params)
      redirect_to [:admin, @question]
    else
      render :edit
    end
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Question not found'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_test, only: %i[index new create]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def index; end

  def new
    @question = @test.questions.build
  end

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to @question.test
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    redirect_to @question.test
    flash[:notice] = 'Question removed successfully'
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Question not found'
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} question"
    else
      "Create New #{question.test.title} question"
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} question"
    else
      "Create New #{question.test.title} question"
    end
  end
end

app/views/questions/_form.erb
<%= form_for [@test, @question], local: true do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/questions/index.erb
<%= render 'shared/flash' %>
<h1><%= @test.title %> test questions:</h1>
<ul>
  <% @test.questions.each do |question| %>
  <li>
    <%= link_to question.body, question_path(question) %>
  </li>
  <% end %>
</ul>
<%= link_to 'Go Back', :root %> | <%= link_to 'Add new question', new_test_question_path %>

app/views/questions/index.html.erb
<h1><%= @test.title %> test questions:</h1>

<table>
  <tr>
    <th>Question</th>
    <th colspan="3">Action</th>
  </tr>
  <%= render @test.questions %>
</table>

<%= link_to 'Go Back', :root %> | <%= link_to 'Add new question', new_test_question_path %>

app/views/questions/show.erb
<h1><%= @question.test.title %> question</h1>

<p><%= @question.body %></p>

<%= link_to 'Go Back', test_questions_path(@question.test) %>