config/routes.rb
Rails.application.routes.draw do
  get 'feedback/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :feedbacks, only: [:new, :create]
  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
end

app/models/admin.rb
class Admin < User
  validates :firstname, :lastname, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :text, presence: true

  belongs_to :question

  scope :correct, -> { where(correct: true) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
BADGE_RULES = [
  ['Прохождение всех тестов категории', 'all_tests_by_category_passed?'],
  ['Прохождение теста с первой попытки', 'passed_test_on_the_first_try?'],
  ['Прохождение всех тестов определенного уровня', 'passed_all_tests_by_level?']
].freeze

class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges

  def self.rules
    BADGE_RULES
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true

  has_many :tests

  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Model

  attr_accessor :title, :body

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true
  validate :validate_answers_count

  belongs_to :test
  has_many :answers

  private

  def validate_answers_count
    errors.add(:answers, 'You must add from 1 to 4 answers') unless (1..4).include?(answers.size)
  end
end

app/models/test.rb
class Test < ActiveRecord::Base
  validates :title, presence: true
  validates :level, numericality: { only_integer: true }, inclusion: 1..10
  validates :title, uniqueness: { scope: :level }

  has_many :test_passages
  has_many :users, through: :test_passages
  belongs_to :author, class_name: 'User'
  belongs_to :category
  has_many :questions

  scope :by_level, ->(level) { where(level: level) }
  scope :easy, -> { by_level(0..1) }
  scope :medium, -> { by_level(2..4) }
  scope :hard, -> { by_level(5..Float::INFINITY) }

  scope :by_category, ->(category) {
    joins(:category)
      .where(categories: { title: category })
      .order(title: :desc)
  }

  def self.titles_by_category(category)
    by_category(category).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ActiveRecord::Base
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def current_question_number
    questions_count - next_questions.count
  end

  def questions_count
    test.questions.count
  end

  def success_rate
    correct_questions * 100 / questions_count
  end

  def completed?
    current_question.nil?
  end

  def passed?
    return false unless completed?
    success_rate > 85
  end

  def remaining_time
    (expires_at - Time.current).to_i
  end

  def time_is_out?
    remaining_time <= 0
  end

  private

  def expires_at
    return created_at + 1.year unless test.timer
    created_at + test.timer.seconds
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_questions
    return test.questions unless current_question
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def before_validation_set_current_question
    self.current_question = next_questions.first if test.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable,
         :lockable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :tests_created, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists
  has_many :user_badges
  has_many :badges, through: :user_badges


  def test_passage(test)
    test_passages.order(created_at: :desc).find_by(test_id: test.id)
  end

  def passed_tests_by_category(category)
    tests.where(category: category).distinct
  end
  def passed_tests_by_level(level)
    tests.by_level(level).distinct
  end

  def fullname
    "#{firstname} #{lastname}"
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_admin_badge, only: [:show, :edit, :update, :destroy]

  # GET /admin/badges
  def index
    @badges = Badge.all
  end

  # GET /admin/badges/1
  def show
  end

  # GET /admin/badges/new
  def new
    @badge = Badge.new
  end

  # GET /admin/badges/1/edit
  def edit
  end

  # POST /admin/badges
  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('.success_create')
    else
      render :new
    end
  end

  # PATCH/PUT /admin/badges/1
  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge], notice: t('.success_update')
    else
      render :edit
    end
  end

  # DELETE /admin/badges/1
  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: t('.success_destroy')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_badge
    @badge = Badge.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def badge_params
    params.require(:badge).permit(:title, :image, :rule, :rule_parameter)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    super
    set_flash_message(:notice, :signed_in_greeting, fullname: current_user.fullname)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_TYPE = { alert: 'danger', notice: 'primary' }.freeze

  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'GitHub', "https://github.com/#{author}/#{repo}", target: :blank
  end

  def flash_messages
    html = flash.map do |key, message|
      content_tag :div, message, class: "alert alert-#{FLASH_TYPE[key.to_sym]}"
    end
    safe_join(html, '')
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} question"
    else
      "Create New #{question.test.title} question"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_result
    if @test_passage.passed?
      "<h1 style='color: green'>Your success rate: #{@test_passage.success_rate}%. Test passed!</h2>".html_safe
    else
      "<h1 style='color: red'>Your success rate: #{@test_passage.success_rate}%. Test failed!</h2>".html_safe
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= image_tag((badge.image), class: 'rounded-circle size-200px') %></td>
  <td><%= badge.title %></td>
  <td>
    <%= link_to t('show'),
                admin_badge_path(badge),
                class: 'btn btn-primary' %>
    <%= link_to t('edit'),
                edit_admin_badge_path(badge),
                class: 'btn btn-primary' %>
    <%= link_to t('delete'),
                admin_badge_path(badge),
                method: :delete, data: { confirm: t('sure?') },
                class: 'btn btn-danger form-inline-link' %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-5">
    <%= render 'shared/errors', resource: @badge %>

    <%= form_with model: [:admin, @badge], local: true do |form| %>
      <div class="form-group">

        <p>
          <%= form.label :image %>
          <%= form.text_field :image, class: 'form-control' %>
        </p>

        <p>
          <%= form.label :title %>
          <%= form.text_field :title, class: 'form-control' %>
        </p>

        <p>
          <%= form.label :rule %>
          <%= form.select :rule, options_for_select(Badge.rules, selected: @badge.rule), { prompt: true }, { class: 'form-control' }  %>
        </p>

        <p>
          <%= form.label :rule_parameter %>
          <%= form.text_field :rule_parameter, class: 'form-control' %>
        </p>

        <p><%= form.submit class: 'btn btn-primary' %></p>
      </div>
    <% end %>
    <%= link_to t('back'), admin_tests_path %>
  </div>
</div>

app/views/admin/badges/edit.html.erb
<h1>Editing Admin Badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_badge %> |
<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1><%= t('.all_badges') %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= link_to t('.new_badge'), new_admin_badge_path, class: 'btn btn-primary' %>
      <table class="table table-bordered mt-3">
        <thead>
        <tr>
          <th><%= t('.name') %></th>
          <th><%= t('.rule') %></th>
          <th><%= t('.actions') %></th>
        </tr>
        </thead>
        <tbody>
          <%= render @badges %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/badges/new.html.erb
<h1>New Admin Badge</h1>

<%= render 'form', admin_badge: @admin_badge %>

<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= image_tag(@badge.image) %>
      <p>
        <%= @badge.title %>
      </p>

      <p>
        <%= @badge.rule_parameter %>
      </p>

      <%= link_to t('edit'), edit_admin_badge_path(@badge) %> |
      <%= link_to t('back'), admin_tests_path %>
    </div>
  </div>
</div>

app/views/badges/_badge.html.erb
<tr>
  <td><%= image_tag((badge.image), class: 'rounded-circle size-200px') %></td>
  <td><%= badge.title %></td>
</tr>

app/views/badges/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1><%= t('.all_badges') %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <table class="table table-bordered">
        <thead>
        <tr>
          <th><%= t('.image') %></th>
          <th><%= t('.name') %></th>
        </tr>
        </thead>
        <tbody>
          <%= render Badge.all %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <h1><%= t('.my_badges') %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th><%= t('.image') %></th>
            <th><%= t('.name') %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @badges %>
        </tbody>
      </table>
    </div>
  </div>
</div>