config/routes.rb
Rails.application.routes.draw do
  get 'feedback/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :feedbacks, only: [:new, :create]
  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
end

app/models/admin.rb
class Admin < User
  validates :firstname, :lastname, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :text, presence: true

  belongs_to :question

  scope :correct, -> { where(correct: true) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
BADGE_RULES = [
  ['Прохождение всех тестов категории', 'all_tests_by_category_passed?'],
  ['Прохождение теста с первой попытки', 'passed_test_on_the_first_try?'],
  ['Прохождение всех тестов определенного уровня', 'passed_all_tests_by_level?']
].freeze

class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges

  def self.rules
    BADGE_RULES
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true

  has_many :tests

  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Model

  attr_accessor :title, :body

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true
  validate :validate_answers_count

  belongs_to :test
  has_many :answers

  private

  def validate_answers_count
    errors.add(:answers, 'You must add from 1 to 4 answers') unless (1..4).include?(answers.size)
  end
end

app/models/test.rb
class Test < ActiveRecord::Base
  validates :title, presence: true
  validates :level, numericality: { only_integer: true }, inclusion: 1..10
  validates :title, uniqueness: { scope: :level }

  has_many :test_passages
  has_many :users, through: :test_passages
  belongs_to :author, class_name: 'User'
  belongs_to :category
  has_many :questions

  scope :by_level, ->(level) { where(level: level) }
  scope :easy, -> { by_level(0..1) }
  scope :medium, -> { by_level(2..4) }
  scope :hard, -> { by_level(5..Float::INFINITY) }

  scope :by_category, ->(category) {
    joins(:category)
      .where(categories: { title: category })
      .order(title: :desc)
  }

  def self.titles_by_category(category)
    by_category(category).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ActiveRecord::Base
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def current_question_number
    questions_count - next_questions.count
  end

  def questions_count
    test.questions.count
  end

  def success_rate
    correct_questions * 100 / questions_count
  end

  def completed?
    current_question.nil?
  end

  def passed?
    return false unless completed?
    success_rate > 85
  end

  def remaining_time
    (expires_at - Time.current).to_i
  end

  def time_is_out?
    remaining_time <= 0
  end

  private

  def expires_at
    return created_at + 1.year unless test.timer
    created_at + test.timer.seconds
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_questions
    return test.questions unless current_question
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def before_validation_set_current_question
    self.current_question = next_questions.first if test.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable,
         :lockable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :tests_created, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists
  has_many :user_badges
  has_many :badges, through: :user_badges


  def test_passage(test)
    test_passages.order(created_at: :desc).find_by(test_id: test.id)
  end

  def passed_tests_by_category(category)
    tests.where(category: category).distinct
  end
  def passed_tests_by_level(level)
    tests.by_level(level).distinct
  end

  def fullname
    "#{firstname} #{lastname}"
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_TYPE = { alert: 'danger', notice: 'primary' }.freeze

  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'GitHub', "https://github.com/#{author}/#{repo}", target: :blank
  end

  def flash_messages
    html = flash.map do |key, message|
      content_tag :div, message, class: "alert alert-#{FLASH_TYPE[key.to_sym]}"
    end
    safe_join(html, '')
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} question"
    else
      "Create New #{question.test.title} question"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_result
    if @test_passage.passed?
      "<h1 style='color: green'>Your success rate: #{@test_passage.success_rate}%. Test passed!</h2>".html_safe
    else
      "<h1 style='color: red'>Your success rate: #{@test_passage.success_rate}%. Test failed!</h2>".html_safe
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark header">
  <%= link_to 'Test Guru', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCustom" aria-controls="navbarsExampleCenteredNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-md-end" id="navbarCustom">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Admin', admin_tests_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Gists', admin_gists_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Badges', admin_badges_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Guru', root_path, class: 'nav-link' %>
      </li>
      <span class="navbar-text">Welcome,
        <%= current_user.email %>
      </span>
      <li class="nav-item">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-12">
        Test-Guru &copy; <%= current_year %>
        <br>
        <%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com/', target: :blank %>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        Vyacheslav Zavertanniy | <%= github_url('oozywaters', 'test-guru') %> |
        <%= link_to t('.feedback'), new_feedback_path %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark header">
  <%= link_to 'Test Guru', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCustom" aria-controls="navbarsExampleCenteredNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-md-end" id="navbarCustom">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Guru', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Badges', badges_path, class: 'nav-link' %>
        </li>
        <span class="navbar-text">Welcome,
          <%= current_user.email %>
        </span>
        <li class="nav-item">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestGuru</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'admin/header' %>
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= flash_messages %>
    </div>
  </div>
</div>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestGuru</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= flash_messages %>
    </div>
  </div>
</div>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= t('.header', count: resource.errors.count) %>:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.erb
<% if flash[:notice] %>
  <div class="row">
    <div class="notice col-12">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>