config/routes.rb
Rails.application.routes.draw do
  get 'feedback/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :feedbacks, only: [:new, :create]
  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true
  validate :validate_answers_count

  belongs_to :test
  has_many :answers

  private

  def validate_answers_count
    errors.add(:answers, 'You must add from 1 to 4 answers') unless (1..4).include?(answers.size)
  end
end

app/models/test_passage.rb
class TestPassage < ActiveRecord::Base
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def current_question_number
    questions_count - next_questions.count
  end

  def questions_count
    test.questions.count
  end

  def success_rate
    correct_questions * 100 / questions_count
  end

  def completed?
    current_question.nil?
  end

  def passed?
    return false unless completed?
    success_rate > 85
  end

  def remaining_time
    (expires_at - Time.current).to_i
  end

  def time_is_out?
    remaining_time <= 0
  end

  private

  def expires_at
    return created_at + 1.year unless test.timer
    created_at + test.timer.seconds
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_questions
    return test.questions unless current_question
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def before_validation_set_current_question
    self.current_question = next_questions.first if test.present?
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result gist]
  before_action :check_timer, only: %i[update]

  def show;
    if @test_passage.questions_count == 0
      flash[:notice] = 'This test has no questions yet.'
      redirect_to tests_path
    end
  end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      UserBadgesService.new(@test_passage).call
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call

    flash_options = if result.html_url
                      create_gist!(result.html_url)
                      { notice: t('.success', link: result.html_url) }
                    else
                      { alert: t('.failure') }
                    end

    redirect_to @test_passage, flash_options
  end

  private

  def create_gist!(url)
    current_user.gists.create!(
      question: @test_passage.current_question,
      url: url
    )
  end

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def check_timer
    if @test_passage.time_is_out?
      flash[:notice] = 'Time is out! Try again later.'
      redirect_to result_test_passage_path(@test_passage)
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1>The <%= @test_passage.test.title %> test was completed</h1>

<%= test_result %>

<%= link_to t('back'), tests_path %>

app/views/test_passages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Passing the <%= @test_passage.test.title %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p>
        Question <%= @test_passage.current_question_number %> of
        <%= @test_passage.questions_count %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p>
        Time left: <%= content_tag :span, '', id: 'timer', data: { timeleft: @test_passage.remaining_time } %>
      </p>
    </div>
  </div>
  <div class="progress mb-2">
    <%= content_tag :div,
                    class: 'progress-bar',
                    data: {
                        question_number: @test_passage.current_question_number,
                        questions_count: @test_passage.questions_count
                    } do %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-12">
      <p>
        <%= @test_passage.current_question.body %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
        <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :text, include_hidden: false do |b| %>
          <p>
            <%= b.check_box id: "answer_ids_#{b.object.id}" %>
            <%= b.label %>
          </p>
        <% end %>
        <%= link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post, class: 'btn btn-primary' %>
        <%= form.submit t('next'), class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>